# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QFile, QTextStream

import style.breeze_resources


class Ui_App(object):
    def setupUi(self, App):
        App.setObjectName("App")
        App.resize(440, 597)
        App.setAutoFillBackground(False)
        self.Search = QtWidgets.QTabWidget(App)
        self.Search.setGeometry(QtCore.QRect(0, 0, 431, 541))
        self.Search.setObjectName("Search")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 40, 421, 491))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 417, 487))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.StockGraph = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.StockGraph.setGeometry(QtCore.QRect(10, 10, 391, 191))
        self.StockGraph.setObjectName("StockGraph")
        self.StockDataView = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.StockDataView.setGeometry(QtCore.QRect(10, 230, 391, 231))
        self.StockDataView.setObjectName("StockDataView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(230, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(110, 10, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.Search.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Search.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Search.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Search.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Search.addTab(self.tab_5, "")

        self.retranslateUi(App)
        self.Search.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(App)

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        App.setWindowTitle(_translate("App", "App"))
        self.pushButton.setText(_translate("App", "search"))
        self.Search.setTabText(self.Search.indexOf(self.tab), _translate("App", "search"))
        self.Search.setTabText(self.Search.indexOf(self.tab_2), _translate("App", "paper trade"))
        self.Search.setTabText(self.Search.indexOf(self.tab_3), _translate("App", "portfolio"))
        self.Search.setTabText(self.Search.indexOf(self.tab_4), _translate("App", "Page"))
        self.Search.setTabText(self.Search.indexOf(self.tab_5), _translate("App", "Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    App = QtWidgets.QWidget()

    file = QFile(":/dark.qss")
    file.open(QFile.ReadOnly | QFile.Text)
    stream = QTextStream(file)
    app.setStyleSheet(stream.readAll())

    ui = Ui_App()
    ui.setupUi(App)
    App.show()
    sys.exit(app.exec_())
